### ISSUE TITLE
empty jupyter tree

### ISSUE THREAD

**Issue by aaita92** [ZEMUSHKA/coursera-aml-docker#2]
I followed the instruction, I downloaded the image and then when I ran:
docker run -it -p 127.0.0.1:8080:8080 --name coursera-aml-1 zimovnov/coursera-aml-docker.
the jupyter tree was empty.
Is it the complete and right procedure, or I forgot some steps?

**Comment by aaita92** [comment]
the right procedure consist to open a new terminal on docker, writing the command:
 **`docker exec -i -t (container ID) /bin/bash`**

**Comment by henrytdsimmons** [comment]
I also have this problem, not sure how to resolve it.

**Comment by ZEMUSHKA** [comment]
Oh, I see. You need to follow https://github.com/hse-aml/intro-to-dl#prepare-resources-inside-jupyter-notebooks-for-local-setups-only (basically downloading code and data inside the Jupyter).
